trigger:
- master

pool:
  vmImage: windows-latest
stages:
  - stage: TrivyScan
    jobs:
      - job: RunTrivy
        displayName: 'Run Trivy Scan on Local Repo'
        steps:
          - checkout: none  # 👈 This is important to prevent cloning anything
 
          - task: PowerShell@2
            displayName: 'Run Trivy on local WebGoat'
            inputs:
              targetType: 'inline'
              script: |
                cd "C:\Gitlab_CI_Integration\Trivy\trivy_0.62.1_windows-64bit"
                .\trivy.exe fs "C:\Gitlab_CI_Integration\Trivy\juice-shop-master" --exit-code=0 > "C:\Gitlab_CI_Integration\Trivy\Reports\SoftwareCompoAanalysis_juice.txt"